[package]
name = "huffle"
version = "0.2.0"
authors = ["hx64 <xiayuxuan@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2.33"
clap = "2.33.3"
